### ISSUE TITLE
Firefox local extension analysis not working

### ISSUE THREAD

**Issue by acheong08** [Tuhinshubhra/ExtAnalysis#22]
ERROR:root:Traceback (most recent call last):
  File "/Users/$whoami/ExtAnalysis/frontend/api.py", line 122, in view
    exts = lexts.firefox()
  File "/Users/$whoami/ExtAnalysis/core/localextensions.py", line 184, in firefox
    if default_profile_path != "":
UnboundLocalError: local variable 'default_profile_path' referenced before assignment
<img width="481" alt="Screen Shot 2020-10-21 at 9 18 53 PM" src="https://user-images.githubusercontent.com/36258159/96725012-06f2a000-13e3-11eb-9142-dd24e667938e.png">

**Comment by Tuhinshubhra** [comment]
What OS are you using?

**Comment by nawfalona** [comment]
Debian!

**Comment by acheong08** [comment]
MacOS

**Comment by acheong08** [comment]
Worked after setting the 'default_profile_path' manually in core/localextensions.py
