### ISSUE TITLE
Stuck on "extracting intels".

### ISSUE THREAD

**Issue by PinkDev1** [Tuhinshubhra/ExtAnalysis#23]
When scanning a big extension, sometimes ExtAnalysis will get permanently stuck on the Extracting intels phase.
For example, try scanning the bitwarden add-on.
It'll get stuck on `[i] Extracting intels from: C:\Program Files\ExtAnalysis\lab\bitwarden_free_password_manager-1.48.1-an+fx\background.js`

Python 3.9.0
Firefox 85.0.1 (64-bit)
Started scanning via the Firefox Web URL (https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/)

**Comment by Tuhinshubhra** [comment]
Try disabling intels which you don't need to extract from the settings page and try once more.

**Comment by PinkDev1** [comment]
Ah, it seems it wasn't getting stuck. It's just that it takes so long processing that it seems like it gets stuck. pls consider adding a `--verbose-level x` option :P
