### ISSUE TITLE
Report Details

### ISSUE THREAD

**Issue by keyboardcrunch** [Tuhinshubhra/ExtAnalysis#4]
I think it would be beneficial to show on the Reports Analysis page a browser icon to identify if the extension was for Chrome or Firefox, as well as on the Scan Info section of the report.

This would help differentiate scans of the same extensions between the two browsers.

**Comment by Tuhinshubhra** [comment]
Thank you for the suggestion! I will work on adding it asap

**Comment by Tuhinshubhra** [comment]
Hi I have added the browser name in the scan info section as requested.
 
![image](https://user-images.githubusercontent.com/28696468/57708348-cb4c9600-7686-11e9-8467-523874e230d3.png)

Thank you for making ExtAnalysis better. Feel free to reopen in case you have any other issues!
