### ISSUE TITLE
.crx Error: File is not a zip file

### ISSUE THREAD

**Issue by glaucozf** [Tuhinshubhra/ExtAnalysis#40]
I'm not able to perform any analysis, it always says it's not a zip file... Thank´s for help!!!!

Extension:
https://chromewebstore.google.com/detail/clockify-time-tracker/pmjeegjhjdlccodhacdgbgfagbpmccpe

Here's the log:

[i] Accessed Main page
[i] Downloader says: save_path is /mnt/c/Users/glauco.florio/Downloads/extanalysis/ExtAnalysis/lab/Clockfy.crx
Download URL: https://clients2.google.com/service/update2/crx?response=redirect&os=win&arch=x86-64&os_arch=x86-64&nacl_arch=x86-64&prod=chromecrx&prodchannel=unknown&prodversion=81.0.4044.138&acceptformat=crx2,crx3&x=id%3Dpmjeegjhjdlccodhacdgbgfagbpmccpe%26uc
[+] Extension downloaded successfully: /mnt/c/Users/glauco.florio/Downloads/extanalysis/ExtAnalysis/lab/Clockfy.crx
[i] analyze func: Clockfy.crx
[i] Trying to unzip /mnt/c/Users/glauco.florio/Downloads/extanalysis/ExtAnalysis/lab/Clockfy.crx to /mnt/c/Users/glauco.florio/Downloads/extanalysis/ExtAnalysis/lab/Clockfy
ERROR:root:Traceback (most recent call last):
  File "/mnt/c/Users/glauco.florio/Downloads/extanalysis/ExtAnalysis/core/analyze.py", line 135, in analyze
    zip_contents = zipfile.ZipFile(ext_path, 'r')
  File "/usr/lib/python3.9/zipfile.py", line 1259, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1326, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

[!] Something went wrong while unzipping extension
Error: File is not a zip file

**Comment by Tuhinshubhra** [comment]
@glaucozf it should be fixed, closing the issue.
