### ISSUE TITLE
Installation folder

### ISSUE THREAD

**Issue by fegimo5751** [Tuhinshubhra/ExtAnalysis#9]
I cannot scan extensions installed locally in Mozilla Firefox on Win10. 

Error in log: "Something went wrong while reading firefox profie.ini"

In which directory do I have to place the ExtAnalysis folder? Profile folder? Program folder?

Analyzing an extension from the Addon store works fine.

**Comment by Tuhinshubhra** [comment]
Do you mind providing me with full log? 

Also is your firefox installed in the default location or a custom location?

**Comment by fegimo-new** [comment]
This is the only line in the log: "Something went wrong while reading firefox profie.ini"
Yes, Firefox (program and profile) is installed in the default location.
Does it matter where I install ExtAnalysis?
Also, Firefox profile information is in profiles.ini, not profile.ini or profie.ini
Profiles.ini is in User\AppData\Roaming\Mozilla\Firefox

**Comment by fegimo-new** [comment]
ps: it's a great tool. Analyzing extensions is very important, they are a huge security and privacy risk.

**Comment by Tuhinshubhra** [comment]
```
Does it matter where I install ExtAnalysis?

- Well not really! 
```

```
Also, Firefox profile information is in profiles.ini, not profile.ini or profie.ini

- It's just a typo on the logging part i believe the code part has it right

https://github.com/Tuhinshubhra/ExtAnalysis/blob/a0af30a02d432b383039b90c875efbfb41fa5c09/core/localextensions.py#L101
```

**Anyways i'll try to reproduce the error again and let you know if i need any more info.**

```
ps: it's a great tool. Analyzing extensions is very important, they are a huge security and privacy risk.

- Thanks, and yes they are!
```

**Comment by Tuhinshubhra** [comment]
Hey @fegimo-new I have pushed a potential fix for the bug, could you clone ExtAnalysis again and lemme know if It's fixed on your end?

**Comment by fegimo-new2** [comment]
Yes, now it works like a charm! 

The topic is very important. Consider offering a pre-compiled executable for Windows/Mac and letting folks at Gacks.net and others know. Fixing the extenstions security/privacy nightmare is one of the top priorities for Firefox/Chrome. 

The same is true for mobile/smartphone apps and trackers.  Just a few days ago there was a huge article in the New York Times about how they steal and sell your data.

**Comment by Tuhinshubhra** [comment]
Thanks for confirming, and sure I'll try to do it.

Also if you have any more feature requests feel free to open another issue, closing this now.
